import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Head from "next/head";

const JetBrainsMono = JetBrains_Mono({
  variable: "--font-jet",
  subsets: ['latin'],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${JetBrainsMono.variable}  antialiased`}
      >

        <Header style={{
          position:'fixed',
          zIndex:'1000px'
        }}/>
        {children}
      </body>
    </html>
  );
}
